print("HELLO")
print("Please open the file 'preregRS.Rmd'.")
print("In order to compile 'preregRS.Rmd' to HTML click on the 'knit' button above the editor pane.")
library(utils)
file.edit("preregRS.Rmd")
